[package]
name = "sif"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
hel.workspace = true
hel-sys.workspace = true
lock_api = "0.4"
managarm.workspace = true
managarm-arch.workspace = true
parking_lot = "0.12"
thiserror = "2.0"
uacpi-sys.workspace = true
zerocopy.workspace = true
