
#include "../kernel.hpp"

namespace memory = frigg::memory;
namespace debug = frigg::debug;

namespace thor {

// --------------------------------------------------------
// Debugging functions
// --------------------------------------------------------

void BochsSink::print(char c) {
	frigg::arch_x86::ioOutByte(0xE9, c);
}
void BochsSink::print(const char *str) {
	while(*str != 0)
		frigg::arch_x86::ioOutByte(0xE9, *str++);
}

// --------------------------------------------------------
// ThorRtThreadState
// --------------------------------------------------------

ThorRtThreadState::ThorRtThreadState() {
	memset(&threadTss, 0, sizeof(frigg::arch_x86::Tss64));
	frigg::arch_x86::initializeTss64(&threadTss);
}

void ThorRtThreadState::activate() {
	// set the current general state pointer
	asm volatile ( "mov %0, %%gs:0x08" : : "r" (&generalState) : "memory" );
	
	// setup the thread's tss segment
	ThorRtCpuSpecific *cpu_specific;
	asm volatile ( "mov %%gs:0x18, %0" : "=r" (cpu_specific) );
	threadTss.ist1 = cpu_specific->tssTemplate.ist1;
	
	frigg::arch_x86::makeGdtTss64Descriptor(cpu_specific->gdt, 4,
			&threadTss, sizeof(frigg::arch_x86::Tss64));
	asm volatile ( "ltr %w0" : : "r" ( 0x20 ) );
}

// --------------------------------------------------------
// ThorRtKernelGs
// --------------------------------------------------------

ThorRtKernelGs::ThorRtKernelGs()
: cpuContext(nullptr), generalState(nullptr), syscallStackPtr(nullptr),
		cpuSpecific(nullptr) { }

// --------------------------------------------------------
// Namespace scope functions
// --------------------------------------------------------

void thorRtSetCpuContext(void *context) {
	asm volatile ( "mov %0, %%gs:0" : : "r" (context) : "memory" );
}

void *thorRtGetCpuContext() {
	void *context;
	asm volatile ( "mov %%gs:0, %0" : "=r" (context) );
	return context;
}

extern "C" void thorRtLoadCs(uint16_t selector);

void initializeThisProcessor() {
	auto cpu_specific = memory::construct<ThorRtCpuSpecific>(*thor::kernelAlloc);
	
	// set up the kernel gs segment
	auto kernel_gs = memory::construct<ThorRtKernelGs>(*thor::kernelAlloc);
	kernel_gs->cpuSpecific = cpu_specific;
	frigg::arch_x86::wrmsr(frigg::arch_x86::kMsrIndexGsBase, (uintptr_t)kernel_gs);

	// setup a stack for syscalls
	size_t syscall_stack_size = 0x100000;
	void *syscall_stack_base = thor::kernelAlloc->allocate(syscall_stack_size);
	kernel_gs->syscallStackPtr = (void *)((uintptr_t)syscall_stack_base
			+ syscall_stack_size);

	// setup the gdt
	// note: the tss requires two slots in the gdt
	frigg::arch_x86::makeGdtNullSegment(cpu_specific->gdt, 0);
	frigg::arch_x86::makeGdtCode64SystemSegment(cpu_specific->gdt, 1);
	frigg::arch_x86::makeGdtCode64UserSegment(cpu_specific->gdt, 2);
	frigg::arch_x86::makeGdtFlatData32UserSegment(cpu_specific->gdt, 3);
	frigg::arch_x86::makeGdtTss64Descriptor(cpu_specific->gdt, 4, nullptr, 0);

	frigg::arch_x86::Gdtr gdtr;
	gdtr.limit = 6 * 8;
	gdtr.pointer = cpu_specific->gdt;
	asm volatile ( "lgdt (%0)" : : "r"( &gdtr ) );

	thorRtLoadCs(0x8);
	
	// setup the kernel tss
	frigg::arch_x86::initializeTss64(&cpu_specific->tssTemplate);
	cpu_specific->tssTemplate.ist1 = (uintptr_t)kernel_gs->syscallStackPtr;
	
	frigg::arch_x86::makeGdtTss64Descriptor(cpu_specific->gdt, 4,
			&cpu_specific->tssTemplate, sizeof(frigg::arch_x86::Tss64));
	asm volatile ( "ltr %w0" : : "r" ( 0x20 ) );
	
	// setup the idt
	for(int i = 0; i < 256; i++)
		frigg::arch_x86::makeIdt64NullGate(cpu_specific->idt, i);
	setupIdt(cpu_specific->idt);

	frigg::arch_x86::Idtr idtr;
	idtr.limit = 256 * 16;
	idtr.pointer = cpu_specific->idt;
	asm volatile ( "lidt (%0)" : : "r"( &idtr ) );
}

// note: these symbols have PHYSICAL addresses!
extern "C" void trampoline();
extern "C" uint32_t trampolineStatus;
extern "C" uint32_t trampolinePml4;
extern "C" uint64_t trampolineStack;

// generated by the linker script
extern "C" uint8_t _trampoline_startLma[];
extern "C" uint8_t _trampoline_endLma[];

bool secondaryBootComplete;

extern "C" void thorRtSecondaryEntry() {
	// inform the bsp that we do not need the trampoline area anymore
	frigg::atomic::volatileWrite<bool>(&secondaryBootComplete, true);

	thor::infoLogger->log() << "Hello world from second CPU" << debug::Finish();
	
	initializeThisProcessor();
	
	thor::infoLogger->log() << "AP initialized" << debug::Finish();

	while(true) { }
}

void bootSecondary(uint32_t secondary_apic_id) {
	// copy the trampoline code into low physical memory
	uintptr_t trampoline_addr = (uintptr_t)trampoline;
	size_t trampoline_size = (uintptr_t)_trampoline_endLma - (uintptr_t)_trampoline_startLma;
	ASSERT((trampoline_addr % 0x1000) == 0);
	ASSERT((trampoline_size % 0x1000) == 0);
	memcpy(thor::physicalToVirtual(trampoline_addr), _trampoline_startLma, trampoline_size);
	
	size_t trampoline_stack_size = 0x100000;
	void *trampoline_stack_base = thor::kernelAlloc->allocate(trampoline_stack_size);

	// setup the trampoline data area
	auto status_ptr = thor::accessPhysical<uint32_t>((PhysicalAddr)&trampolineStatus);
	auto pml4_ptr = thor::accessPhysical<uint32_t>((PhysicalAddr)&trampolinePml4);
	auto stack_ptr = thor::accessPhysical<uint64_t>((PhysicalAddr)&trampolineStack);
	secondaryBootComplete = false;
	*pml4_ptr = thor::kernelSpace->getPml4();
	*stack_ptr = ((uintptr_t)trampoline_stack_base + trampoline_stack_size);

	raiseInitAssertIpi(secondary_apic_id);
	raiseInitDeassertIpi(secondary_apic_id);
	raiseStartupIpi(secondary_apic_id, trampoline_addr);
	asm volatile ( "" : : : "memory" );
	
	// wait until the ap wakes up
	thor::infoLogger->log() << "Waiting for AP to wake up" << debug::Finish();
	while(frigg::atomic::volatileRead<uint32_t>(status_ptr) == 0) {
		frigg::atomic::pause();
	}
	
	// allow ap code to initialize the processor
	thor::infoLogger->log() << "AP is booting" << debug::Finish();
	frigg::atomic::volatileWrite<uint32_t>(status_ptr, 2);
	
	// wait until the secondary processor completed its boot process
	// we can re-use the trampoline area after this completes
	while(!frigg::atomic::volatileRead<bool>(&secondaryBootComplete)) {
		frigg::atomic::pause();
	}
	thor::infoLogger->log() << "AP finished booting" << debug::Finish();
}

} // namespace thor

