// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: char_device.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "char_device.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace managarm {
namespace char_device {

void protobuf_ShutdownFile_char_5fdevice_2eproto() {
  delete ClientRequest::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_char_5fdevice_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_char_5fdevice_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ClientRequest::default_instance_ = new ClientRequest();
  ClientRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_char_5fdevice_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_char_5fdevice_2eproto_once_);
void protobuf_AddDesc_char_5fdevice_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_char_5fdevice_2eproto_once_,
                 &protobuf_AddDesc_char_5fdevice_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_char_5fdevice_2eproto {
  StaticDescriptorInitializer_char_5fdevice_2eproto() {
    protobuf_AddDesc_char_5fdevice_2eproto();
  }
} static_descriptor_initializer_char_5fdevice_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int ClientRequest::kCharsFieldNumber;
#endif  // !_MSC_VER

ClientRequest::ClientRequest()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:managarm.char_device.ClientRequest)
}

void ClientRequest::InitAsDefaultInstance() {
}

ClientRequest::ClientRequest(const ClientRequest& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:managarm.char_device.ClientRequest)
}

void ClientRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  chars_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClientRequest::~ClientRequest() {
  // @@protoc_insertion_point(destructor:managarm.char_device.ClientRequest)
  SharedDtor();
}

void ClientRequest::SharedDtor() {
  chars_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void ClientRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ClientRequest& ClientRequest::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_char_5fdevice_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_char_5fdevice_2eproto();
#endif
  return *default_instance_;
}

ClientRequest* ClientRequest::default_instance_ = NULL;

ClientRequest* ClientRequest::New(::google::protobuf::Arena* arena) const {
  ClientRequest* n = new ClientRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientRequest::Clear() {
  if (has_chars()) {
    chars_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool ClientRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:managarm.char_device.ClientRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string chars = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_chars()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:managarm.char_device.ClientRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:managarm.char_device.ClientRequest)
  return false;
#undef DO_
}

void ClientRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:managarm.char_device.ClientRequest)
  // optional string chars = 1;
  if (has_chars()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->chars(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:managarm.char_device.ClientRequest)
}

int ClientRequest::ByteSize() const {
  int total_size = 0;

  // optional string chars = 1;
  if (has_chars()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->chars());
  }

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientRequest::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ClientRequest*>(&from));
}

void ClientRequest::MergeFrom(const ClientRequest& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_chars()) {
      set_has_chars();
      chars_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.chars_);
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void ClientRequest::CopyFrom(const ClientRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientRequest::IsInitialized() const {

  return true;
}

void ClientRequest::Swap(ClientRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientRequest::InternalSwap(ClientRequest* other) {
  chars_.Swap(&other->chars_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string ClientRequest::GetTypeName() const {
  return "managarm.char_device.ClientRequest";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClientRequest

// optional string chars = 1;
bool ClientRequest::has_chars() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ClientRequest::set_has_chars() {
  _has_bits_[0] |= 0x00000001u;
}
void ClientRequest::clear_has_chars() {
  _has_bits_[0] &= ~0x00000001u;
}
void ClientRequest::clear_chars() {
  chars_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_chars();
}
 const ::std::string& ClientRequest::chars() const {
  // @@protoc_insertion_point(field_get:managarm.char_device.ClientRequest.chars)
  return chars_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ClientRequest::set_chars(const ::std::string& value) {
  set_has_chars();
  chars_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:managarm.char_device.ClientRequest.chars)
}
 void ClientRequest::set_chars(const char* value) {
  set_has_chars();
  chars_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:managarm.char_device.ClientRequest.chars)
}
 void ClientRequest::set_chars(const char* value, size_t size) {
  set_has_chars();
  chars_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:managarm.char_device.ClientRequest.chars)
}
 ::std::string* ClientRequest::mutable_chars() {
  set_has_chars();
  // @@protoc_insertion_point(field_mutable:managarm.char_device.ClientRequest.chars)
  return chars_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ClientRequest::release_chars() {
  clear_has_chars();
  return chars_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ClientRequest::set_allocated_chars(::std::string* chars) {
  if (chars != NULL) {
    set_has_chars();
  } else {
    clear_has_chars();
  }
  chars_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), chars);
  // @@protoc_insertion_point(field_set_allocated:managarm.char_device.ClientRequest.chars)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace char_device
}  // namespace managarm

// @@protoc_insertion_point(global_scope)
